apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app
  name: frontend
  namespace: default
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP 
    targetPort: 5000
  # - name: metrics
  #   port: 8000
  #   protocol: TCP 
  #   targetPort: 8000
  selector:
    app: flask-app
  type: NodePort